name: enjoy_plus_hm
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  fluttertoast: ^8.2.8
  flutter_html: ^3.0.0-alpha.4
  shared_preferences: ^2.3.2
  event_bus: ^2.0.1
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.5
  permission_handler: ^11.3.1
  geolocator: ^13.0.1
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  image_path_android: "assets/icons/bozai.png"
  image_path_ios: "assets/icons/bozai.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/icons/bozai.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/icons/bozai.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground_inset: 16 # only available for Android 8.0 devices and above
  adaptive_icon_monochrome: "assets/icons/bozai.png" # only available for Android 13 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"


flutter:
  uses-material-design: true
  assets:
    - assets/tabs/home_active.png
    - assets/tabs/home_default.png
    - assets/tabs/my_default.png
    - assets/tabs/my_active.png
    - assets/images/avatar_1.jpg
    - assets/images/avatar_2.jpg
    - assets/images/banner@2x.jpg
    - assets/images/blank@2x.png
    - assets/images/house_nav_icon@2x.png
    - assets/images/house_profile_icon@2x.png
    - assets/images/marker.png
    - assets/images/notice@2x.png
    - assets/images/repair_nav_icon@2x.png
    - assets/images/repair_profile_icon@2x.png
    - assets/images/share_poster.png
    - assets/images/visitor_nav_icon@2x.png
    - assets/images/visitor_profile_icon@2x.png
    - assets/images/idcard1.png
    - assets/images/idcard2.png
    - assets/icons/bozai.png